NDF/NDF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls',namespace="main")),
]

NDF/main/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='login_user'),
    url(r'^login/$', views.LoginView.as_view(), name='login_user'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout_user'),
    url(r'^stud_profile/$', views.stud_profile, name='stud_profile'),
    url(r'^rules/$', views.rules, name='rules'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^no_dues_apply/$', views.no_dues_apply, name='no_dues_apply'),
    url(r'^stud_full_dept/$', views.stud_full_dept, name='stud_full_dept'),
    url(r'^stud_full_lab/$', views.stud_full_lab, name='stud_full_lab'),
    url(r'^faculty_profile/$', views.faculty_profile, name='faculty_profile'),
    # url(r'^library_profile/$', views.library_profile, name='library_profile'),
    # url(r'^caretaker_profile/$', views.caretaker_profile, name='caretaker_profile'),
    # url(r'^gymkhana_profile/$', views.gymkhana_profile, name='gymkhana_profile'),
    # url(r'^assireg_profile/$', views.assireg_profile, name='assireg_profile'),
    url(r'^stud_nodues/$', views.stud_nodues, name='stud_nodues'),
    url(r'^stud_dues/$', views.stud_dues, name='stud_dues'),
    url(r'^stud_search/$', views.stud_search, name='stud_search'),
    url(r'^hostel_update/$', views.hostel_update, name='hostel_update'),
    # url(r'^onlinecc_profile/$', views.onlinecc_profile, name='onlinecc_profile'),
    # url(r'^cc_profile/$', views.cc_profile, name='cc_profile'),
    # url(r'^thesis_manager_profile/$', views.thesis_manager_profile, name='thesis_manager_profile'),
    # url(r'^lab_profile/$', views.lab_profile, name='lab_profile'),
    # url(r'^hod_profile/$', views.hod_profile, name='hod_profile'),
    # url(r'^account_profile/$', views.account_profile, name='account_profile'),
    url(r'^search_faculties/$',views.search_faculties, name='search_faculties'),
    url(r'^add_faculty/$',views.add_faculty, name='add_faculty'),
    # url(r'^update_status/$',views.update_status, name='update_status'),
    # url(r'^update_remarks/$',views.update_remarks, name='update_remarks'),
    # url(r'^update_status/$', views.update_status, name='update_status'),
    # url(r'^update_remarks/$', views.update_remarks, name='update_remarks'),
    # url(r'^update_lab_status/$', views.update_lab_status, name='update_lab_status'),
    # url(r'^update_lab_remarks/$', views.update_lab_remarks, name='update_lab_remarks'),
    url(r'^update_faculty_status/$', views.update_faculty_status, name='update_faculty_status'),
    # url(r'^update_faculty_remarks/$', views.update_faculty_remarks, name='update_faculty_remarks'),
    # url(r'^search_students/$', views.search_students, name='search_students'),
    # url(r'^add_student/$', views.add_student, name='add_student'),
    url(r'^delete_student/$', views.delete_student, name='delete_student'),
    url(r'^faculty_pending/$', views.faculty_pending, name='faculty_pending'),
    url(r'^faculty_approved/$', views.faculty_approved, name='faculty_approved'),
    url(r'^faculty_rejected/$', views.faculty_rejected, name='faculty_rejected'),
    url(r'^dept_admin$', views.dept_admin, name='dept_admin'),
    url(r'^add_lab$', views.add_lab, name='add_lab'),
    url(r'^delete_lab/$', views.delete_lab, name='delete_lab'),

]

    #url(r'^stud_profile/(?P<username>\w+)/', views.stud_profile, name='stud_overall'),
    #url(r'^stud_profile/(.*)/dept$', views.stud_full_dept, name='stud_dept'),
    #url(r'^stud_profile/(.*)/lab$',views.stud_full_lab , name='stud_lab'),


#index is view name

NDF/main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from .constants import * #LOGIN_SERVER, ROLES
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ['name', 'webmail', 'department', 'hostel']


class FacultyForm(forms.ModelForm):

    class Meta:
        model = Faculty
        fields = ['webmail', 'department','name']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class LoginForm(forms.Form):
    username = forms.CharField(required=True, label='Webmail')
    password = forms.CharField(required=True, widget=forms.PasswordInput)
    login_server = forms.ChoiceField(required=True, choices=LOGIN_SERVER)
    role = forms.ChoiceField(required=True, choices=ROLES)

    def clean_role(self):
        valid_roles = [
       "Student", "Faculty", "Lab", "Caretaker", "Warden", "Gymkhana", "OnlineCC", "CC", "Thesis Manager", "Library", "Assistant Registrar", "HOD", "Account", "Admin"
        ]
        role = self.cleaned_data.get('role')
        if role not in valid_roles:
            raise  ValidationError(_('Invalid Role'), code='invalid')
        return role

    def clean_login_server(self):
        valid_servers = ['202.141.80.9', '202.141.80.10', '202.141.80.11',
                         '202.141.80.12', '202.141.80.13']
        login_server = self.cleaned_data.get('login_server')
        if login_server not in valid_servers:
            raise ValidationError(_('Invalid Login Server'), code='invalid')
        return login_server

NDF/main/views.py
from .models import *
from django.contrib.auth import *
from django.http import *
from django.shortcuts import *
from django.utils import timezone
from .forms import *
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.urls import reverse_lazy
from django.utils.http import is_safe_url
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from poplib import *
from django.db.models import Q

class LoginView(View):
    template_name = 'main/login.html'
    port = 995
    next = ''

    def get(self, request):
        self.next = request.GET.get('next', '')
        webmail = request.user.username
        if request.user.is_authenticated() and not request.user.is_superuser:
            if(Student.objects.filter(webmail=webmail)):
                return redirect('/stud_profile')
            elif(Faculty.objects.filter(webmail=webmail)):
                return redirect('/faculty_profile')
            elif(DeptAdmin.objects.filter(webmail=webmail)):
                return redirect('/dept_admin')
            else:
                return redirect('/stud_nodues')
        args = dict(form=LoginForm(None), next=self.next)
        return render(request, self.template_name, args)

    def post(self, request):
        redirect_to = request.POST.get('next', self.next)
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            login_server = form.cleaned_data.get('login_server')
            role = form.cleaned_data.get('role')
            # em = '%s@iitg.ernet.in' % (username)
            # mail = POP3_SSL(login_server)
            # mail.user(username)
            # try:
            #     mail.pass_(password)
            #     mail.quit()
            # except:
            #     form.add_error(None, 'Wrong Username or Password.')
            #     return render(request, self.template_name, dict(form=form))

            # if not(User.objects.filter(username=username)):
            #     new_user = User.objects.create_user(username=username,
            #                     email=em,
            #                      password=password)
            #     new_user.save()

            user = auth.authenticate(username=username, password=password)
            if user is not None :
                if not is_safe_url(url=redirect_to, host=request.get_host()):
                    auth.login(request=request, user=user)
                    if role == "Student":
                        try:
                            student = Student.objects.get(webmail=username)
                        except Student.DoesNotExist:
                            student = None
                        if student is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_profile')
                    elif role == "Faculty":
                        try:
                            fac = Faculty.objects.get(webmail=username)
                        except Faculty.DoesNotExist:
                            fac = None
                        if fac is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/faculty_profile')
                    elif role == "Warden":
                        try:
                            warden = Warden.objects.get(webmail=username)
                        except Warden.DoesNotExist:
                            warden = None

                        if warden is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')

                    elif role == "Caretaker":
                        try:
                            caretaker = Caretaker.objects.get(webmail=username)
                        except Caretaker.DoesNotExist:
                            caretaker = None

                        if caretaker is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')

                    elif role == "Gymkhana":
                        try:
                            gymkhana = Gymkhana.objects.get(webmail=username)
                        except Gymkhana.DoesNotExist:
                            gymkhana = None
                        if gymkhana is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')
                    elif role == "OnlineCC":
                        try:
                            onlinecc = OnlineCC.objects.get(webmail=username)
                        except OnlineCC.DoesNotExist:
                            onlinecc = None
                        if onlinecc is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')
                    elif role == "CC":
                        try:
                            cc = CC.objects.get(webmail=username)
                        except CC.DoesNotExist:
                            cc = None
                        if cc is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')
                    elif role == "Thesis Manager":
                        try:
                            thesis_manager = SubmitThesis.objects.get(webmail=username)
                        except SubmitThesis.DoesNotExist:
                            thesis_manager = None
                        if thesis_manager is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')
                    elif role == "Library":
                        try:
                            library = Library.objects.get(webmail=username)
                        except Library.DoesNotExist:
                            library = None
                        if library is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')
                    elif role == "Assistant Registrar":
                        try:
                            assistant_registrar = Assistant_registrar.objects.get(webmail=username)
                        except Assistant_registrar.DoesNotExist:
                            assistant_registrar = None
                        if assistant_registrar is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')
                    elif role == "HOD":
                        try:
                            hod = HOD.objects.get(webmail=username)
                        except HOD.DoesNotExist:
                            hod = None
                        if hod is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')
                    elif role == "Account":
                        try:
                            account = Account.objects.get(webmail=username)
                        except Account.DoesNotExist:
                            account = None
                        if account is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')
                    elif role == "Lab":
                        try:
                            lab = Labs.objects.get(webmail=username)
                        except Labs.DoesNotExist:
                            lab = None
                        if lab is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:
                            return redirect('/stud_nodues')
                    elif role == "Admin":
                        try:
                            admin = DeptAdmin.objects.get(webmail=username)
                        except DeptAdmin.DoesNotExist:
                            admin = None
                        if admin is None:
                            form.add_error(None, 'Role mismatch')
                            return render(request, self.template_name, dict(form=form))
                        else:

NDF/main/templates/main/rules.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Rules{{ student.name }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 10px;
            bottom: 0;
            width : 100%;
        position: fixed;
    }
  </style>
</head>
<body>
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav hidden-xs">
      <h4>Welcome {{ student.name }}!</h4>
    <ul class="nav nav-pills nav-stacked">
        <li><a href="{% url 'main:stud_profile' %}">Overall status</a></li>
                <li class="active"><a href="{% url 'main:rules' %}">Instructions</a></li>
                <li><a href="{% url 'main:logout_user' %}">Log out</a></li>
      </ul><br>
    </div>
    <br>
    <div class="col-sm-9">
      <div class="well">
        <h4>Instructions :</h4>
            <p>Write instructions here </p>
      </div>
    </div>

    </div>
  </div>

<div id="wrapper">
		<div id="header"></div>
		<div id="content"></div>
		<div id="footer"></div>
	</div>
<footer class="container-fluid text-center">
 <p>&copy; 2017 IIT Guwahati</p>
    <p style="font-size:1.0em; text-align:center">Developed By :  &nbsp&nbsp <a href="https://www.facebook.com/meet.555.patoliya" style="color:#169FD8;text-decoration:none;">Meet Patoliya</a></p>
</footer>

</body>
</html>

NDF/main/templates/main/stud_full_dept.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Department Detail of{{ student.name }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 10px;
            bottom: 0;
            width : 100%;
        }



        .dropbtn {
            background-color: #4CAF50;
            color: white;
            padding: 16px;
            font-size: 16px;
            border: none;
            cursor: pointer;
        }

        .dropbtn:hover, .dropbtn:focus {
            background-color: #3e8e41;
        }

        #faculty_search {
            background-image: url({% static "img/searchicon.png" %});
            background-position: 14px 12px;
            background-size: 25px 25px;
            background-repeat: no-repeat;
            font-size: 16px;
            padding: 14px 20px 12px 45px;
            border: none;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f6f6f6;
            min-width: 230px;
            overflow: auto;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 1;
        }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        .dropdown a:hover {
            background-color: #ddd
        }

        .show {
            display: block;
        }


    </style>
</head>

<script>
    $(document).ready(function () {
        $('#faculty_search').keyup(function () {

            var searchinput = $('#faculty_search').val();
            if (searchinput.length >= 1) {
                $.ajax({
                    type: "POST",
                    url: "/search_faculties/",
                    data: {
                        csrfmiddlewaretoken: '{{csrf_token}}',
                        searchquery: searchinput
                    },
                    success: function (data) {
                        //add elements to dropdown list
                        $('.items').remove();
                        var json1 = data.faculties_searched;
                        items = [];
                        for (var key in json1) {
                            if (items.length < 10) {
                                var value = json1[key];
                                items.push('<a class="items" id="' + key + '" onclick="addfaculty(this.id)">' + value + '</a>');
                            }
                        }
                        $('#myDropdown').append(items.join(''));
                    },
                    error: function () {
                        //
                    }
                });
            }
            else if (searchinput.length == 0) {
                $('.items').remove();
            }
        });
    });

    $(function () {
        $('.dropbtn').click(function (e) {
            $('.dropdown-content').slideToggle();
            e.stopPropagation();
        });
        $('.dropdown-content').click(function (e) {
            e.stopPropagation();
        });
        $(document).click(function () {
            $('.dropdown-content').slideUp();
        });
    });

    function addfaculty(id) {
        var faculty_webmail = id;
        if (confirm("Are you sure to add faculty?")) {
            $.ajax({
                type: "GET",
                url: "/add_faculty",
                data: {
                    faculty_webmail: faculty_webmail
                },
                success: function (data) {
                    var name = data.name;
                    if (name != " ") {
                        var remarks = data.remarks;
                        var status = data.status;
                        var temp = '<tr>' +
                            '<td>' + name + '</td>' +
                            '<td>{% if stat is 2 %}<span style="color: #11B54A">Approved</span>{% elif stat is 3 %}<span style="color:#e92916">Not Approved</span>{% else %}<span style="color:#e92916">Pending</span>{% endif %}' +
                            '</td>' +
                            '<td>' + remarks + '</td>' +
                            '<td>None</td>' +
                            '</tr>';


                        $("#facultylist").append($(temp).fadeIn('slow'));
                    }
                    else {
                        alert("Faculty was already added");
                    }
                },
                error: function () {
                    //
                }
            });
        }

        $('.dropdown-content').slideUp();

    }

</script>
<body>
<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-3 sidenav hidden-xs">
            <h4>Welcome {{ student.name }}!</h4>
            <ul class="nav nav-pills nav-stacked">
                <li><a href="{% url 'main:stud_profile' %}">Overall status</a></li>
                <li><a href="{% url 'main:rules' %}">Instructions</a></li>
                <li><a href="{% url 'main:logout_user' %}">Log out</a></li>
            </ul>
            <br>
        </div>
        <br>
        <div class="col-sm-9">
            <div class="well">
                <div class="dropdown">
                    <button class="dropbtn">Add faculty</button>

                    <div id="myDropdown" class="dropdown-content">
                        <input type="text" placeholder="Search by name or webmail.." id="faculty_search">


                    </div>
                </div>
                <br>
                <br>
                <h5>
                    Add BTP/MTP professors and other concerned faculties before you apply for clearing dues
                </h5>

            </div>
               <table id="faculty_list" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Faculty Name</th>
                        <th>No Dues Status</th>
                        <th>Remarks</th>
                        <th>Last Updated</th>
                    </tr>
                    </thead>
                    <tbody id="facultylist">
                    {% for facultyname, stat, remarks, time in details %}
                        <tr>
                            <td>
                                {{ facultyname }}
                            </td>
                            <td>
                                {% if stat is 2 %}
                                    <span style="color: #11B54A">Approved</span>
                                {% elif stat is 3 %}
                                    <span style="color:#e92916">Not Approved</span>
                                {% else %}
                                    <span style="color:#e92916">Pending</span>
                                {% endif %}
                            </td>
                            <td>
                                {{ remarks }}
                            </td>
                            <td>
                                {{ time }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<div id="wrapper">
    <div id="header"></div>
    <div id="content"></div>
    <div id="footer"></div>
</div>
<footer class="container-fluid text-center">
   <p>&copy; 2017 IIT Guwahati</p>
    <p style="font-size:1.0em; text-align:center">Developed By :  &nbsp&nbsp <a href="https://www.facebook.com/meet.555.patoliya" style="color:#169FD8;text-decoration:none;">Meet Patoliya</a></p>
</footer>

</body>
</html>

NDF/main/templates/main/stud_full_lab.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Lab Detail of {{ stud.name }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 10px;
            bottom: 0;
            width: 100%;
            position : fixed;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-3 sidenav hidden-xs">
            <h4>Welcome {{ stud.name }}!</h4>
            <ul class="nav nav-pills nav-stacked">
                <li><a href="{% url 'main:stud_profile' %}">Overall status</a></li>
                <li><a href="{% url 'main:rules' %}">Instructions</a></li>
                <li><a href="{% url 'main:logout_user' %}">Log out</a></li>
            </ul>
            <br>
        </div>
        <br>
        <div class="col-sm-9">
            <div class="well">
                <h4>Details of Department</h4>
            </div>
            <table id="lab_list" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>HOD</th>
                    <th>Webmail</th>
                    <th>No Dues Status</th>
                    <th>Remarks</th>
                    <th>Last Updated</th>
                </tr>
                </thead>
                <tbody id="lablist">
                    <tr>
                        <td>
                            {{ hod.name }}
                        </td>
                        <td>{{ hod.webmail }}</td>
                        <td>
                            {% if stud.hod_dues is False %}
                                <span style="color: #11B54A">Clearence Given</span>
                            {% else %}
                                <span style="color:#e92916">Clearence Pending</span>
                            {% endif %}
                        </td>
                        <td>
                            {{ stud.hod_remarks }}
                        </td>
                        <td>
                            {{ stud.hod_update_time }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <table id="lab_list" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Labs/Library</th>
                    <th>Incharge</th>
                    <th>No Dues Status</th>
                    <th>Remarks</th>
                    <th>Last Updated</th>
                </tr>
                </thead>
                <tbody id="lablist">
                {% for labname, incharge, stat, remarks, time in details %}
                    <tr>
                        <td>
                            {{ labname }}
                        </td>
                        <td>{{ incharge }}</td>
                        <td>
                            {% if stat is False %}
                                <span style="color: #11B54A">Clearence Given</span>
                            {% else %}
                                <span style="color:#e92916">Clearence Pending</span>
                            {% endif %}
                        </td>
                        <td>
                            {{ remarks }}
                        </td>
                        <td>
                            {{ time }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>


        </div>
    </div>

</div>

<div id="wrapper">
    <div id="header"></div>
    <div id="content"></div>
    <div id="footer"></div>
</div>
<footer class="container-fluid text-center">
    <p>&copy; 2017 IIT Guwahati</p>
    <p style="font-size:1.0em; text-align:center">Developed By : &nbsp&nbsp <a
            href="https://www.facebook.com/meet.555.patoliya" style="color:#169FD8;text-decoration:none;">Meet
        Patoliya</a></p>
</footer>

</body>
</html>